# Generated by Django 2.2.4 on 2019-10-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField()),
                ('expense_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('income_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('income_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('user_income_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('total_expense', models.IntegerField()),
                ('income_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.Income')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('user_expense_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('total_expense', models.IntegerField()),
                ('expense_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('user_expense_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.UserExpense')),
                ('user_income_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.UserIncome')),
            ],
        ),
    ]
