# Generated by Django 2.2.4 on 2019-10-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name_plural': 'Expense'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name_plural': 'Income'},
        ),
        migrations.AlterModelOptions(
            name='userexpense',
            options={'verbose_name_plural': 'User Expenses'},
        ),
        migrations.AlterModelOptions(
            name='userincome',
            options={'verbose_name_plural': 'User Incomes'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_expense_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_income_ID',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='expense_ID',
        ),
        migrations.RemoveField(
            model_name='userincome',
            name='income_ID',
        ),
        migrations.AddField(
            model_name='expense',
            name='user_expense_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.UserExpense'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='user_income_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.UserIncome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userexpense',
            name='user_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userincome',
            name='user_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='user_expense_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='user_income_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
