# Generated by Django 2.2.4 on 2019-10-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0002_auto_20191003_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userincome',
            old_name='total_expense',
            new_name='total_income',
        ),
    ]
