# Generated by Django 2.2.4 on 2019-10-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0008_auto_20191004_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user_expense_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.UserExpense'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_income_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.UserIncome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='user_expense_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='user_income_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
