# Generated by Django 2.2.4 on 2019-10-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0010_auto_20191004_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_expense_ID',
            new_name='userExpense',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user_income_ID',
            new_name='userIncome',
        ),
        migrations.RenameField(
            model_name='userexpense',
            old_name='user_ID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userincome',
            old_name='user_ID',
            new_name='user',
        ),
    ]
