# Generated by Django 2.2.4 on 2019-10-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0011_auto_20191004_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='userExpense',
        ),
        migrations.RemoveField(
            model_name='income',
            name='userIncome',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userincome',
            name='user',
        ),
    ]
