# Generated by Django 2.2.4 on 2019-10-03 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0012_auto_20191004_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user_expense_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.UserExpense'),
        ),
        migrations.AddField(
            model_name='income',
            name='user_income_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.UserIncome'),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='user_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
        ),
        migrations.AddField(
            model_name='userincome',
            name='user_ID',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.User'),
        ),
    ]
