# Generated by Django 2.2.4 on 2019-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0013_auto_20191004_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_cause',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='income',
            name='income_source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
