# Generated by Django 2.2.4 on 2019-10-03 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0014_auto_20191004_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('total_savings', models.IntegerField()),
                ('user_ID', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PM.User')),
            ],
            options={
                'verbose_name_plural': 'Savings',
            },
        ),
    ]
