# Generated by Django 2.2.4 on 2019-10-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0016_auto_20191004_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_savings',
            field=models.IntegerField(default=0),
        ),
    ]
