# Generated by Django 2.2.4 on 2019-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0019_auto_20191004_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savings',
            name='savings_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ID',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
