# Generated by Django 2.2.4 on 2019-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0021_auto_20191004_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass123', max_length=30),
        ),
    ]
