# Generated by Django 2.2.4 on 2019-12-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Manager', '0002_auto_20191204_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_savings', models.IntegerField()),
                ('savings_use', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Savings',
            },
        ),
    ]
